import os


REFRESH_SECONDS = int(os.getenv("REFRESH_SECONDS", "30"))
DEFAULT_TOP_N = int(os.getenv("DEFAULT_TOP_N", "30"))
TOMORROW_TOP_N = int(os.getenv("TOMORROW_TOP_N", "36"))
MIN_TURNOVER = float(os.getenv("MIN_TURNOVER", "50000000"))
MAX_RECOMMENDED_GAIN = float(os.getenv("MAX_RECOMMENDED_GAIN", "12"))
MAX_BUYABLE_GAIN_MAIN = float(os.getenv("MAX_BUYABLE_GAIN_MAIN", "6.5"))
MAX_BUYABLE_GAIN_GROWTH = float(os.getenv("MAX_BUYABLE_GAIN_GROWTH", "10"))
TUSHARE_TOKEN = os.getenv("TUSHARE_TOKEN", "")
ALLOW_SLOW_QUOTE_FALLBACK = os.getenv("ALLOW_SLOW_QUOTE_FALLBACK", "0").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
STATE_PATH = os.getenv("STATE_PATH", ".runtime/recommendation_state.json")
STRATEGY_STATUS_PATH = os.getenv("STRATEGY_STATUS_PATH", ".runtime/strategy_status.json")
QUOTE_SNAPSHOT_PATH = os.getenv("QUOTE_SNAPSHOT_PATH", ".runtime/latest_quotes.json")
QUOTE_SNAPSHOT_MAX_AGE_SECONDS = int(os.getenv("QUOTE_SNAPSHOT_MAX_AGE_SECONDS", "21600"))
QUOTE_SNAPSHOT_MIN_ROWS = int(os.getenv("QUOTE_SNAPSHOT_MIN_ROWS", "50"))
VALIDATION_DB_PATH = os.getenv("VALIDATION_DB_PATH", ".runtime/strategy_validation.sqlite3")
HISTORY_FACTOR_LIMIT = int(os.getenv("HISTORY_FACTOR_LIMIT", "40"))
HISTORY_FACTORS_FETCH_ON_REQUEST = os.getenv("HISTORY_FACTORS_FETCH_ON_REQUEST", "0").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
HISTORY_FACTORS_MAX_REQUEST_FETCHES = int(os.getenv("HISTORY_FACTORS_MAX_REQUEST_FETCHES", "8"))
HISTORY_CACHE_PATH = os.getenv("HISTORY_CACHE_PATH", ".runtime/history_cache.sqlite3")
HISTORY_CACHE_FRESHNESS_HOURS = int(os.getenv("HISTORY_CACHE_FRESHNESS_HOURS", "18"))
VALIDATION_AUTO_UPDATE_ENABLED = os.getenv("VALIDATION_AUTO_UPDATE_ENABLED", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
VALIDATION_AUTO_UPDATE_INITIAL_DELAY_SECONDS = int(os.getenv("VALIDATION_AUTO_UPDATE_INITIAL_DELAY_SECONDS", "180"))
VALIDATION_AUTO_UPDATE_INTERVAL_SECONDS = int(os.getenv("VALIDATION_AUTO_UPDATE_INTERVAL_SECONDS", "1800"))
VALIDATION_AUTO_UPDATE_BATCH_SIZE = int(os.getenv("VALIDATION_AUTO_UPDATE_BATCH_SIZE", "40"))
VALIDATION_AUTO_UPDATE_MAX_CODES_PER_RUN = int(os.getenv("VALIDATION_AUTO_UPDATE_MAX_CODES_PER_RUN", "160"))
VALIDATION_AUTO_UPDATE_HISTORY_DAYS = int(os.getenv("VALIDATION_AUTO_UPDATE_HISTORY_DAYS", "220"))
VALIDATION_AUTO_UPDATE_STRATEGIES = os.getenv("VALIDATION_AUTO_UPDATE_STRATEGIES", "")
VALIDATION_AUTO_SNAPSHOT_ENABLED = os.getenv("VALIDATION_AUTO_SNAPSHOT_ENABLED", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
VALIDATION_AUTO_SNAPSHOT_TIME = os.getenv("VALIDATION_AUTO_SNAPSHOT_TIME", "15:00")
VALIDATION_AUTO_SNAPSHOT_MARKET = os.getenv("VALIDATION_AUTO_SNAPSHOT_MARKET", "all")
VALIDATION_TRADE_COST_PCT = float(os.getenv("VALIDATION_TRADE_COST_PCT", "0.25"))
VALIDATION_PRIMARY_ENTRY_MODE = os.getenv("VALIDATION_PRIMARY_ENTRY_MODE", "open").lower()
VALIDATION_SLIPPAGE_HIGH_TURNOVER_PCT = float(os.getenv("VALIDATION_SLIPPAGE_HIGH_TURNOVER_PCT", "0.05"))
VALIDATION_SLIPPAGE_MID_TURNOVER_PCT = float(os.getenv("VALIDATION_SLIPPAGE_MID_TURNOVER_PCT", "0.12"))
VALIDATION_SLIPPAGE_LOW_TURNOVER_PCT = float(os.getenv("VALIDATION_SLIPPAGE_LOW_TURNOVER_PCT", "0.25"))
VALIDATION_SLIPPAGE_MICRO_TURNOVER_PCT = float(os.getenv("VALIDATION_SLIPPAGE_MICRO_TURNOVER_PCT", "0.45"))
STRATEGY_DECAY_MIN_REAL_SAMPLES = int(os.getenv("STRATEGY_DECAY_MIN_REAL_SAMPLES", "20"))
STRATEGY_DECAY_WIN_RATE_FLOOR = float(os.getenv("STRATEGY_DECAY_WIN_RATE_FLOOR", "42"))
STRATEGY_DECAY_AVG_RETURN_FLOOR = float(os.getenv("STRATEGY_DECAY_AVG_RETURN_FLOOR", "0"))
STRATEGY_DECAY_SOFT_WEIGHT = float(os.getenv("STRATEGY_DECAY_SOFT_WEIGHT", "0.5"))
STRATEGY_RETIRE_WINRATE = float(os.getenv("STRATEGY_RETIRE_WINRATE", "48"))
PORTFOLIO_MAX_POSITIONS = int(os.getenv("PORTFOLIO_MAX_POSITIONS", "10"))
PORTFOLIO_SINGLE_CAP = float(os.getenv("PORTFOLIO_SINGLE_CAP", "0.15"))
PORTFOLIO_THEME_CAP = float(os.getenv("PORTFOLIO_THEME_CAP", "0.35"))
PORTFOLIO_GROSS_RISK_ON = float(os.getenv("PORTFOLIO_GROSS_RISK_ON", "1.0"))
PORTFOLIO_GROSS_BALANCED = float(os.getenv("PORTFOLIO_GROSS_BALANCED", "0.7"))
PORTFOLIO_GROSS_RISK_OFF = float(os.getenv("PORTFOLIO_GROSS_RISK_OFF", "0.4"))
PORTFOLIO_DD_LEVEL_1 = float(os.getenv("PORTFOLIO_DD_LEVEL_1", "8.0"))
PORTFOLIO_DD_FACTOR_1 = float(os.getenv("PORTFOLIO_DD_FACTOR_1", "0.7"))
PORTFOLIO_DD_LEVEL_2 = float(os.getenv("PORTFOLIO_DD_LEVEL_2", "15.0"))
PORTFOLIO_DD_FACTOR_2 = float(os.getenv("PORTFOLIO_DD_FACTOR_2", "0.4"))
PAPER_TRADING_DB_PATH = os.getenv("PAPER_TRADING_DB_PATH", ".runtime/paper_trading.sqlite3")
PAPER_TRADING_HISTORY_DAYS = int(os.getenv("PAPER_TRADING_HISTORY_DAYS", "220"))
PAPER_TRADING_SPREAD_CAPITAL_BY_HOLDING_DAYS = os.getenv("PAPER_TRADING_SPREAD_CAPITAL_BY_HOLDING_DAYS", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
ENABLE_EVENT_RISK = os.getenv("ENABLE_EVENT_RISK", "0").lower() in ("1", "true", "yes", "on")
EVENT_RISK_CACHE_PATH = os.getenv("EVENT_RISK_CACHE_PATH", ".runtime/event_risk.json")
EVENT_RISK_CACHE_HOURS = int(os.getenv("EVENT_RISK_CACHE_HOURS", "24"))
EVENT_RISK_LOOKAHEAD_DAYS = int(os.getenv("EVENT_RISK_LOOKAHEAD_DAYS", "30"))
EVENT_RISK_UNLOCK_WARN_RATIO = float(os.getenv("EVENT_RISK_UNLOCK_WARN_RATIO", "3.0"))
EVENT_RISK_UNLOCK_HIGH_RATIO = float(os.getenv("EVENT_RISK_UNLOCK_HIGH_RATIO", "8.0"))
EVENT_RISK_PLEDGE_WARN_RATIO = float(os.getenv("EVENT_RISK_PLEDGE_WARN_RATIO", "35.0"))
EVENT_RISK_PLEDGE_HIGH_RATIO = float(os.getenv("EVENT_RISK_PLEDGE_HIGH_RATIO", "55.0"))
EVENT_RISK_REPORT_WINDOW_DAYS = int(os.getenv("EVENT_RISK_REPORT_WINDOW_DAYS", "5"))
EVENT_RISK_REDUCTION_LOOKBACK_DAYS = int(os.getenv("EVENT_RISK_REDUCTION_LOOKBACK_DAYS", "120"))
EVENT_RISK_PENALTY_LOW = float(os.getenv("EVENT_RISK_PENALTY_LOW", "4.0"))
EVENT_RISK_PENALTY_MEDIUM = float(os.getenv("EVENT_RISK_PENALTY_MEDIUM", "9.0"))
EVENT_RISK_PENALTY_HIGH = float(os.getenv("EVENT_RISK_PENALTY_HIGH", "18.0"))
EVENT_RISK_MAX_PENALTY = float(os.getenv("EVENT_RISK_MAX_PENALTY", "30.0"))
EVENT_RISK_HARD_PENALTY = float(os.getenv("EVENT_RISK_HARD_PENALTY", "24.0"))
EVENT_RISK_HARD_FILTER = os.getenv("EVENT_RISK_HARD_FILTER", "0").lower() in ("1", "true", "yes", "on")
ENABLE_FUNDAMENTALS = os.getenv("ENABLE_FUNDAMENTALS", "0").lower() in ("1", "true", "yes", "on")
FUNDAMENTAL_CACHE_PATH = os.getenv("FUNDAMENTAL_CACHE_PATH", ".runtime/fundamentals.json")
FUNDAMENTAL_CACHE_HOURS = int(os.getenv("FUNDAMENTAL_CACHE_HOURS", "24"))
FUNDAMENTAL_FETCH_LIMIT = int(os.getenv("FUNDAMENTAL_FETCH_LIMIT", "200"))
FACTOR_IC_PATH = os.getenv("FACTOR_IC_PATH", ".runtime/factor_ic.json")
ENABLE_FACTOR_IC_WEIGHTING = os.getenv("ENABLE_FACTOR_IC_WEIGHTING", "0").lower() in ("1", "true", "yes", "on")
FACTOR_IC_MIN_SAMPLES = int(os.getenv("FACTOR_IC_MIN_SAMPLES", "30"))
FACTOR_IC_WEIGHT_BAND = float(os.getenv("FACTOR_IC_WEIGHT_BAND", "0.3"))
EXIT_STOP_LOSS_PCT = float(os.getenv("EXIT_STOP_LOSS_PCT", "5.0"))
EXIT_TAKE_PROFIT_PCT = float(os.getenv("EXIT_TAKE_PROFIT_PCT", "8.0"))
EXIT_TRAILING_STOP_PCT = float(os.getenv("EXIT_TRAILING_STOP_PCT", "4.0"))
ENABLE_HISTORY_FACTORS = os.getenv("ENABLE_HISTORY_FACTORS", "0").lower() in ("1", "true", "yes", "on")
ENABLE_INLINE_SENTIMENT = os.getenv("ENABLE_INLINE_SENTIMENT", "0").lower() in ("1", "true", "yes", "on")
ENABLE_MARKET_NEWS = os.getenv("ENABLE_MARKET_NEWS", "0").lower() in ("1", "true", "yes", "on")
ENABLE_HOT_RANKS = os.getenv("ENABLE_HOT_RANKS", "0").lower() in ("1", "true", "yes", "on")
ENABLE_INDUSTRY_STRENGTH = os.getenv("ENABLE_INDUSTRY_STRENGTH", "0").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
EASTMONEY_TIMEOUT_SECONDS = float(os.getenv("EASTMONEY_TIMEOUT_SECONDS", "1"))
EASTMONEY_PAGE_SIZE = int(os.getenv("EASTMONEY_PAGE_SIZE", "500"))
EASTMONEY_MAX_PAGES = int(os.getenv("EASTMONEY_MAX_PAGES", "1"))
EASTMONEY_SORT_FIELD = os.getenv("EASTMONEY_SORT_FIELD", "f6")

# 回测校准脚本（calibrate.py）写出的权重覆盖文件；scoring/backtest 启动时若存在则加载。
WEIGHTS_OVERRIDE_PATH = os.getenv("WEIGHTS_OVERRIDE_PATH", ".runtime/weights.json")
TOMORROW_ITERATION_PATH = os.getenv("TOMORROW_ITERATION_PATH", ".runtime/tomorrow_iteration.json")
CALIBRATE_MIN_SAMPLES = int(os.getenv("CALIBRATE_MIN_SAMPLES", "30"))
CALIBRATE_IMPROVE_MARGIN = float(os.getenv("CALIBRATE_IMPROVE_MARGIN", "0.05"))
CALIBRATE_WALK_FORWARD_FOLDS = int(os.getenv("CALIBRATE_WALK_FORWARD_FOLDS", "4"))
CALIBRATE_MIN_COVERAGE = float(os.getenv("CALIBRATE_MIN_COVERAGE", "0.5"))

# 小市值策略的流通市值下限（元），过滤纯壳/退市风险股。默认 8 亿。
SMALLCAP_MIN_FLOAT_CAP = float(os.getenv("SMALLCAP_MIN_FLOAT_CAP", "800000000"))

SUPPORTED_PREFIXES = (
    "600",
    "601",
    "603",
    "605",
    "000",
    "001",
    "002",
    "003",
    "300",
    "301",
    "688",
)

MAIN_BOARD_PREFIXES = ("600", "601", "603", "605", "000", "001", "002", "003")
CHINEXT_PREFIXES = ("300", "301")
STAR_PREFIXES = ("688",)

MARKET_LABELS = {
    "main": "主板",
    "chinext": "创业板",
    "star": "科创板",
}
