import os


REFRESH_SECONDS = int(os.getenv("REFRESH_SECONDS", "30"))
RECOMMENDATION_DISPLAY_LIMIT = int(os.getenv("RECOMMENDATION_DISPLAY_LIMIT", "18"))
DEFAULT_TOP_N = min(int(os.getenv("DEFAULT_TOP_N", str(RECOMMENDATION_DISPLAY_LIMIT))), RECOMMENDATION_DISPLAY_LIMIT)
RECOMMENDATION_MAX_TOP_N = min(int(os.getenv("RECOMMENDATION_MAX_TOP_N", str(RECOMMENDATION_DISPLAY_LIMIT))), RECOMMENDATION_DISPLAY_LIMIT)
TOMORROW_TOP_N = min(int(os.getenv("TOMORROW_TOP_N", str(RECOMMENDATION_DISPLAY_LIMIT))), RECOMMENDATION_DISPLAY_LIMIT)
TODAY_RECOMMENDATION_MIN_SCORE = float(os.getenv("TODAY_RECOMMENDATION_MIN_SCORE", "60"))
SWING_RECOMMENDATION_MIN_SCORE = float(os.getenv("SWING_RECOMMENDATION_MIN_SCORE", "60"))
TOMORROW_PRIMARY_WATCH_N = int(os.getenv("TOMORROW_PRIMARY_WATCH_N", "5"))
SHORT_TERM_STRATEGY_VERSION = os.getenv("SHORT_TERM_STRATEGY_VERSION", "short_term_v2_observation")
TOMORROW_STRATEGY_VERSION = os.getenv("TOMORROW_STRATEGY_VERSION", "tomorrow_picks_v8_next_day")
SWING_STRATEGY_VERSION = os.getenv("SWING_STRATEGY_VERSION", "swing_2_5d_v2_signal_exit")
VALIDATION_REPLAY_VERSION_SUFFIX = os.getenv("VALIDATION_REPLAY_VERSION_SUFFIX", "replay_v2_production")
TOMORROW_RECOMMENDATION_DISPLAY_LIMIT = int(os.getenv("TOMORROW_RECOMMENDATION_DISPLAY_LIMIT", "8"))
TOMORROW_SNAPSHOT_TOP_N = int(os.getenv("TOMORROW_SNAPSHOT_TOP_N", "36"))
TOMORROW_PRIMARY_MIN_SCORE = float(os.getenv("TOMORROW_PRIMARY_MIN_SCORE", "68"))
TOMORROW_BACKUP_MIN_SCORE = float(os.getenv("TOMORROW_BACKUP_MIN_SCORE", "45"))
TOMORROW_MAX_PRIMARY_PER_THEME = int(os.getenv("TOMORROW_MAX_PRIMARY_PER_THEME", "2"))
TOMORROW_MAX_DISPLAY_PER_THEME = int(os.getenv("TOMORROW_MAX_DISPLAY_PER_THEME", "5"))
RECOMMENDATION_MAX_DISPLAY_PER_THEME = int(os.getenv("RECOMMENDATION_MAX_DISPLAY_PER_THEME", "3"))
TOMORROW_MID_GAIN_MIN_PCT = float(os.getenv("TOMORROW_MID_GAIN_MIN_PCT", "4.5"))
TOMORROW_MID_GAIN_MAX_PCT = float(os.getenv("TOMORROW_MID_GAIN_MAX_PCT", "7.0"))
TOMORROW_MID_GAIN_WEAK_CLOSE_LOCATION = float(os.getenv("TOMORROW_MID_GAIN_WEAK_CLOSE_LOCATION", "0.6"))
TOMORROW_MID_GAIN_WEAK_CLOSE_PENALTY = float(os.getenv("TOMORROW_MID_GAIN_WEAK_CLOSE_PENALTY", "7"))
TOMORROW_HIGH_OPEN_SKIP_PCT = float(os.getenv("TOMORROW_HIGH_OPEN_SKIP_PCT", "3.0"))
FACTOR_COVERAGE_ALERT_ZERO_RATIO = float(os.getenv("FACTOR_COVERAGE_ALERT_ZERO_RATIO", "0.30"))
SWING_MIN_HISTORY_FACTOR_COVERAGE = float(os.getenv("SWING_MIN_HISTORY_FACTOR_COVERAGE", "0.30"))
SWING_DEGRADED_DISPLAY_LIMIT = int(os.getenv("SWING_DEGRADED_DISPLAY_LIMIT", "8"))
TOMORROW_PRIMARY_MAX_RISK_PENALTY = float(os.getenv("TOMORROW_PRIMARY_MAX_RISK_PENALTY", "12"))
TOMORROW_PRIMARY_MIN_OVERHEAT_DAMP = float(os.getenv("TOMORROW_PRIMARY_MIN_OVERHEAT_DAMP", "0.72"))
TOMORROW_PRIMARY_MAX_SIXTY_DAY_PCT = float(os.getenv("TOMORROW_PRIMARY_MAX_SIXTY_DAY_PCT", "90"))
TOMORROW_PRIMARY_MAX_YTD_PCT = float(os.getenv("TOMORROW_PRIMARY_MAX_YTD_PCT", "130"))
MIN_TURNOVER = float(os.getenv("MIN_TURNOVER", "50000000"))
MAX_RECOMMENDED_GAIN = float(os.getenv("MAX_RECOMMENDED_GAIN", "12"))
MAX_BUYABLE_GAIN_MAIN = float(os.getenv("MAX_BUYABLE_GAIN_MAIN", "6.5"))
MAX_BUYABLE_GAIN_GROWTH = float(os.getenv("MAX_BUYABLE_GAIN_GROWTH", "10"))
TUSHARE_TOKEN = os.getenv("TUSHARE_TOKEN", "")
ALLOW_SLOW_QUOTE_FALLBACK = os.getenv("ALLOW_SLOW_QUOTE_FALLBACK", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
STATE_PATH = os.getenv("STATE_PATH", ".runtime/recommendation_state.json")
RECOMMENDATION_SNAPSHOT_PATH = os.getenv("RECOMMENDATION_SNAPSHOT_PATH", ".runtime/latest_recommendations.json")
RECOMMENDATION_SNAPSHOT_MAX_AGE_SECONDS = int(os.getenv("RECOMMENDATION_SNAPSHOT_MAX_AGE_SECONDS", "300"))
STRATEGY_STATUS_PATH = os.getenv("STRATEGY_STATUS_PATH", ".runtime/strategy_status.json")
DEEPSEEK_ATTRIBUTION_PATH = os.getenv("DEEPSEEK_ATTRIBUTION_PATH", ".runtime/deepseek_attribution.json")
QUOTE_SNAPSHOT_PATH = os.getenv("QUOTE_SNAPSHOT_PATH", ".runtime/latest_quotes.json")
QUOTE_SNAPSHOT_MAX_AGE_SECONDS = int(os.getenv("QUOTE_SNAPSHOT_MAX_AGE_SECONDS", "21600"))
QUOTE_SNAPSHOT_MIN_ROWS = int(os.getenv("QUOTE_SNAPSHOT_MIN_ROWS", "50"))
VALIDATION_SNAPSHOT_MAX_QUOTE_AGE_SECONDS = int(os.getenv("VALIDATION_SNAPSHOT_MAX_QUOTE_AGE_SECONDS", "3600"))
VALIDATION_ALLOW_LOCAL_QUOTE_SNAPSHOT = os.getenv("VALIDATION_ALLOW_LOCAL_QUOTE_SNAPSHOT", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
VALIDATION_DB_PATH = os.getenv("VALIDATION_DB_PATH", ".runtime/strategy_validation.sqlite3")
VALIDATION_BACKUP_PATH = os.getenv("VALIDATION_BACKUP_PATH", ".runtime/strategy_validation.backup.sqlite3")
HISTORY_FACTOR_LIMIT = int(os.getenv("HISTORY_FACTOR_LIMIT", "40"))
HISTORY_FACTORS_FETCH_ON_REQUEST = os.getenv("HISTORY_FACTORS_FETCH_ON_REQUEST", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
HISTORY_FACTORS_MAX_REQUEST_FETCHES = int(os.getenv("HISTORY_FACTORS_MAX_REQUEST_FETCHES", "8"))
HISTORY_CACHE_PATH = os.getenv("HISTORY_CACHE_PATH", ".runtime/history_cache.sqlite3")
HISTORY_CACHE_FRESHNESS_HOURS = int(os.getenv("HISTORY_CACHE_FRESHNESS_HOURS", "18"))
_DEFAULT_MARKET_DATA_DB_PATH = ".runtime/market_data" if os.path.isdir(".runtime/market_data") else ".runtime/market_data.sqlite3"
MARKET_DATA_DB_PATH = os.getenv("MARKET_DATA_DB_PATH", _DEFAULT_MARKET_DATA_DB_PATH)
VALIDATION_AUTO_UPDATE_ENABLED = os.getenv("VALIDATION_AUTO_UPDATE_ENABLED", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
VALIDATION_AUTO_UPDATE_INITIAL_DELAY_SECONDS = int(os.getenv("VALIDATION_AUTO_UPDATE_INITIAL_DELAY_SECONDS", "600"))
VALIDATION_AUTO_UPDATE_INTERVAL_SECONDS = int(os.getenv("VALIDATION_AUTO_UPDATE_INTERVAL_SECONDS", "600"))
VALIDATION_AUTO_UPDATE_START_TIME = os.getenv("VALIDATION_AUTO_UPDATE_START_TIME", "14:30")
VALIDATION_AUTO_UPDATE_UNTIL_TIME = os.getenv("VALIDATION_AUTO_UPDATE_UNTIL_TIME", "23:59")
VALIDATION_AUTO_UPDATE_BATCH_SIZE = int(os.getenv("VALIDATION_AUTO_UPDATE_BATCH_SIZE", "40"))
VALIDATION_AUTO_UPDATE_MAX_CODES_PER_RUN = int(os.getenv("VALIDATION_AUTO_UPDATE_MAX_CODES_PER_RUN", "160"))
VALIDATION_AUTO_UPDATE_HISTORY_DAYS = int(os.getenv("VALIDATION_AUTO_UPDATE_HISTORY_DAYS", "220"))
TOMORROW_INTRADAY_RELAX_UNTIL = os.getenv("TOMORROW_INTRADAY_RELAX_UNTIL", "14:30")
TOMORROW_INTRADAY_RELAX_START = os.getenv("TOMORROW_INTRADAY_RELAX_START", "09:30")
VALIDATION_AUTO_SNAPSHOT_ENABLED = os.getenv("VALIDATION_AUTO_SNAPSHOT_ENABLED", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
VALIDATION_AUTO_SNAPSHOT_TIME = os.getenv("VALIDATION_AUTO_SNAPSHOT_TIME", "15:00")
VALIDATION_CLOSE_ANCHOR_TIME = os.getenv("VALIDATION_CLOSE_ANCHOR_TIME", "15:00")
VALIDATION_AUTO_SNAPSHOT_RETRY_SECONDS = int(os.getenv("VALIDATION_AUTO_SNAPSHOT_RETRY_SECONDS", "600"))
VALIDATION_AUTO_SNAPSHOT_MARKET = os.getenv("VALIDATION_AUTO_SNAPSHOT_MARKET", "all")
VALIDATION_AUTO_SNAPSHOT_STRATEGIES = os.getenv("VALIDATION_AUTO_SNAPSHOT_STRATEGIES", "")
ENABLE_DEEPSEEK_RUNTIME = os.getenv("ENABLE_DEEPSEEK_RUNTIME", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
DEEPSEEK_RERANK_DISABLED_STRATEGIES = os.getenv("DEEPSEEK_RERANK_DISABLED_STRATEGIES", "")
DEEPSEEK_SCHEDULE_ENABLED = os.getenv("DEEPSEEK_SCHEDULE_ENABLED", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
DEEPSEEK_SCHEDULE_STRATEGIES = os.getenv("DEEPSEEK_SCHEDULE_STRATEGIES", "tomorrow_picks")
DEEPSEEK_SCHEDULE_STATE_PATH = os.getenv("DEEPSEEK_SCHEDULE_STATE_PATH", ".runtime/deepseek_schedule.json")
DEEPSEEK_DAILY_CALL_CAP = int(os.getenv("DEEPSEEK_DAILY_CALL_CAP", "11"))
DEEPSEEK_DAILY_PRO_CALL_CAP = int(os.getenv("DEEPSEEK_DAILY_PRO_CALL_CAP", "1"))
DEEPSEEK_LATE_MIN_INTERVAL_SECONDS = int(os.getenv("DEEPSEEK_LATE_MIN_INTERVAL_SECONDS", "300"))
DEEPSEEK_EARLY_REVIEW_LIMIT = int(os.getenv("DEEPSEEK_EARLY_REVIEW_LIMIT", "4"))
DEEPSEEK_LATE_FLASH_REVIEW_LIMIT = int(os.getenv("DEEPSEEK_LATE_FLASH_REVIEW_LIMIT", "6"))
DEEPSEEK_LATE_PRO_REVIEW_LIMIT = int(os.getenv("DEEPSEEK_LATE_PRO_REVIEW_LIMIT", "4"))
DEEPSEEK_VALIDATION_REVIEW_MIN_NEW_DAYS = int(os.getenv("DEEPSEEK_VALIDATION_REVIEW_MIN_NEW_DAYS", "5"))
DEEPSEEK_WRITE_ALPHA_ZERO = os.getenv("DEEPSEEK_WRITE_ALPHA_ZERO", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
VALIDATION_TRADE_COST_PCT = float(os.getenv("VALIDATION_TRADE_COST_PCT", "0.25"))
VALIDATION_PRIMARY_ENTRY_MODE = os.getenv("VALIDATION_PRIMARY_ENTRY_MODE", "open").lower()
VALIDATION_SLIPPAGE_HIGH_TURNOVER_PCT = float(os.getenv("VALIDATION_SLIPPAGE_HIGH_TURNOVER_PCT", "0.05"))
VALIDATION_SLIPPAGE_MID_TURNOVER_PCT = float(os.getenv("VALIDATION_SLIPPAGE_MID_TURNOVER_PCT", "0.12"))
VALIDATION_SLIPPAGE_LOW_TURNOVER_PCT = float(os.getenv("VALIDATION_SLIPPAGE_LOW_TURNOVER_PCT", "0.25"))
VALIDATION_SLIPPAGE_MICRO_TURNOVER_PCT = float(os.getenv("VALIDATION_SLIPPAGE_MICRO_TURNOVER_PCT", "0.45"))
STRATEGY_DECAY_MIN_REAL_SAMPLES = int(os.getenv("STRATEGY_DECAY_MIN_REAL_SAMPLES", "20"))
STRATEGY_DECAY_MIN_REAL_DAYS = int(
    os.getenv("STRATEGY_DECAY_MIN_REAL_DAYS", str(STRATEGY_DECAY_MIN_REAL_SAMPLES))
)
STRATEGY_DECAY_WIN_RATE_FLOOR = float(os.getenv("STRATEGY_DECAY_WIN_RATE_FLOOR", "42"))
STRATEGY_DECAY_AVG_RETURN_FLOOR = float(os.getenv("STRATEGY_DECAY_AVG_RETURN_FLOOR", "0"))
STRATEGY_DECAY_SOFT_WEIGHT = float(os.getenv("STRATEGY_DECAY_SOFT_WEIGHT", "0.5"))
STRATEGY_RETIRE_WINRATE = float(os.getenv("STRATEGY_RETIRE_WINRATE", "48"))
STRATEGY_VALIDATION_MIN_WIN_RATE = float(os.getenv("STRATEGY_VALIDATION_MIN_WIN_RATE", "50"))
STRATEGY_VALIDATION_MAX_AVG_DRAWDOWN_PCT = float(
    os.getenv("STRATEGY_VALIDATION_MAX_AVG_DRAWDOWN_PCT", "-8")
)
PORTFOLIO_MAX_POSITIONS = int(os.getenv("PORTFOLIO_MAX_POSITIONS", "10"))
PORTFOLIO_SINGLE_CAP = float(os.getenv("PORTFOLIO_SINGLE_CAP", "0.15"))
PORTFOLIO_THEME_CAP = float(os.getenv("PORTFOLIO_THEME_CAP", "0.35"))
PORTFOLIO_GROSS_RISK_ON = float(os.getenv("PORTFOLIO_GROSS_RISK_ON", "1.0"))
PORTFOLIO_GROSS_BALANCED = float(os.getenv("PORTFOLIO_GROSS_BALANCED", "0.7"))
PORTFOLIO_GROSS_RISK_OFF = float(os.getenv("PORTFOLIO_GROSS_RISK_OFF", "0.4"))
PORTFOLIO_DD_LEVEL_1 = float(os.getenv("PORTFOLIO_DD_LEVEL_1", "8.0"))
PORTFOLIO_DD_FACTOR_1 = float(os.getenv("PORTFOLIO_DD_FACTOR_1", "0.7"))
PORTFOLIO_DD_LEVEL_2 = float(os.getenv("PORTFOLIO_DD_LEVEL_2", "15.0"))
PORTFOLIO_DD_FACTOR_2 = float(os.getenv("PORTFOLIO_DD_FACTOR_2", "0.4"))
PAPER_TRADING_DB_PATH = os.getenv("PAPER_TRADING_DB_PATH", ".runtime/paper_trading.sqlite3")
PAPER_TRADING_HISTORY_DAYS = int(os.getenv("PAPER_TRADING_HISTORY_DAYS", "220"))
PAPER_TRADING_SPREAD_CAPITAL_BY_HOLDING_DAYS = os.getenv("PAPER_TRADING_SPREAD_CAPITAL_BY_HOLDING_DAYS", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
ENABLE_STANCE_TRACKING = os.getenv("ENABLE_STANCE_TRACKING", "0").lower() in ("1", "true", "yes", "on")
STANCE_TRACKING_HOLDING_DAYS = int(os.getenv("STANCE_TRACKING_HOLDING_DAYS", "5"))
ENABLE_EVENT_RISK = os.getenv("ENABLE_EVENT_RISK", "0").lower() in ("1", "true", "yes", "on")
EVENT_RISK_CACHE_PATH = os.getenv("EVENT_RISK_CACHE_PATH", ".runtime/event_risk.json")
EVENT_RISK_CACHE_HOURS = int(os.getenv("EVENT_RISK_CACHE_HOURS", "24"))
EVENT_RISK_LOOKAHEAD_DAYS = int(os.getenv("EVENT_RISK_LOOKAHEAD_DAYS", "30"))
EVENT_RISK_UNLOCK_WARN_RATIO = float(os.getenv("EVENT_RISK_UNLOCK_WARN_RATIO", "3.0"))
EVENT_RISK_UNLOCK_HIGH_RATIO = float(os.getenv("EVENT_RISK_UNLOCK_HIGH_RATIO", "8.0"))
EVENT_RISK_PLEDGE_WARN_RATIO = float(os.getenv("EVENT_RISK_PLEDGE_WARN_RATIO", "35.0"))
EVENT_RISK_PLEDGE_HIGH_RATIO = float(os.getenv("EVENT_RISK_PLEDGE_HIGH_RATIO", "55.0"))
EVENT_RISK_REPORT_WINDOW_DAYS = int(os.getenv("EVENT_RISK_REPORT_WINDOW_DAYS", "5"))
EVENT_RISK_REDUCTION_LOOKBACK_DAYS = int(os.getenv("EVENT_RISK_REDUCTION_LOOKBACK_DAYS", "120"))
EVENT_RISK_PENALTY_LOW = float(os.getenv("EVENT_RISK_PENALTY_LOW", "4.0"))
EVENT_RISK_PENALTY_MEDIUM = float(os.getenv("EVENT_RISK_PENALTY_MEDIUM", "9.0"))
EVENT_RISK_PENALTY_HIGH = float(os.getenv("EVENT_RISK_PENALTY_HIGH", "18.0"))
EVENT_RISK_MAX_PENALTY = float(os.getenv("EVENT_RISK_MAX_PENALTY", "30.0"))
EVENT_RISK_HARD_PENALTY = float(os.getenv("EVENT_RISK_HARD_PENALTY", "24.0"))
EVENT_RISK_HARD_FILTER = os.getenv("EVENT_RISK_HARD_FILTER", "0").lower() in ("1", "true", "yes", "on")
ENABLE_RISK_BLACKLIST = os.getenv("ENABLE_RISK_BLACKLIST", "1").lower() in ("1", "true", "yes", "on")
RISK_BLACKLIST_PATH = os.getenv("RISK_BLACKLIST_PATH", ".runtime/risk_blacklist.json")
RISK_BLACKLIST_CSV_PATH = os.getenv("RISK_BLACKLIST_CSV_PATH", ".runtime/risk_blacklist.csv")
RISK_BLACKLIST_HARD_FILTER = os.getenv("RISK_BLACKLIST_HARD_FILTER", "1").lower() in ("1", "true", "yes", "on")
RISK_BLACKLIST_HIGH_LEVELS = tuple(
    item.strip().lower()
    for item in os.getenv("RISK_BLACKLIST_HIGH_LEVELS", "high,critical").split(",")
    if item.strip()
)
ENABLE_FUNDAMENTALS = os.getenv("ENABLE_FUNDAMENTALS", "0").lower() in ("1", "true", "yes", "on")
FUNDAMENTAL_CACHE_PATH = os.getenv("FUNDAMENTAL_CACHE_PATH", ".runtime/fundamentals.json")
FUNDAMENTAL_CACHE_HOURS = int(os.getenv("FUNDAMENTAL_CACHE_HOURS", "24"))
FUNDAMENTAL_FETCH_LIMIT = int(os.getenv("FUNDAMENTAL_FETCH_LIMIT", "200"))
FACTOR_IC_PATH = os.getenv("FACTOR_IC_PATH", ".runtime/factor_ic.json")
FACTOR_SNAPSHOT_DB_PATH = os.getenv("FACTOR_SNAPSHOT_DB_PATH", ".runtime/factor_snapshots.sqlite3")
FACTOR_SNAPSHOT_BATCH_SIZE = int(os.getenv("FACTOR_SNAPSHOT_BATCH_SIZE", "200"))
FACTOR_SNAPSHOT_HISTORY_DAYS = int(os.getenv("FACTOR_SNAPSHOT_HISTORY_DAYS", "120"))
ENABLE_FACTOR_IC_WEIGHTING = os.getenv("ENABLE_FACTOR_IC_WEIGHTING", "0").lower() in ("1", "true", "yes", "on")
FACTOR_IC_MIN_SAMPLES = int(os.getenv("FACTOR_IC_MIN_SAMPLES", "30"))
FACTOR_IC_WEIGHT_BAND = float(os.getenv("FACTOR_IC_WEIGHT_BAND", "0.3"))
EXIT_STOP_LOSS_PCT = float(os.getenv("EXIT_STOP_LOSS_PCT", "5.0"))
EXIT_TAKE_PROFIT_PCT = float(os.getenv("EXIT_TAKE_PROFIT_PCT", "8.0"))
EXIT_TRAILING_STOP_PCT = float(os.getenv("EXIT_TRAILING_STOP_PCT", "4.0"))
SWING_VALIDATION_TAKE_PROFIT_PCT = float(os.getenv("SWING_VALIDATION_TAKE_PROFIT_PCT", "8.0"))
SWING_VALIDATION_STOP_LOSS_PCT = float(os.getenv("SWING_VALIDATION_STOP_LOSS_PCT", "5.0"))
SWING_VALIDATION_TRAILING_STOP_PCT = float(os.getenv("SWING_VALIDATION_TRAILING_STOP_PCT", "4.0"))
TOMORROW_AUXILIARY_TAKE_PROFIT_PCT = float(os.getenv("TOMORROW_AUXILIARY_TAKE_PROFIT_PCT", "8.0"))
TOMORROW_AUXILIARY_STOP_LOSS_PCT = float(os.getenv("TOMORROW_AUXILIARY_STOP_LOSS_PCT", "5.0"))
TOMORROW_AUXILIARY_TRAILING_STOP_PCT = float(os.getenv("TOMORROW_AUXILIARY_TRAILING_STOP_PCT", "4.0"))
ENABLE_HISTORY_FACTORS = os.getenv("ENABLE_HISTORY_FACTORS", "1").lower() in ("1", "true", "yes", "on")
ENABLE_INLINE_SENTIMENT = os.getenv("ENABLE_INLINE_SENTIMENT", "0").lower() in ("1", "true", "yes", "on")
ENABLE_MARKET_NEWS = os.getenv("ENABLE_MARKET_NEWS", "0").lower() in ("1", "true", "yes", "on")
ENABLE_DEEPSEEK_NEWS_CONTEXT = os.getenv("ENABLE_DEEPSEEK_NEWS_CONTEXT", "0").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
DEEPSEEK_NEWS_CACHE_PATH = os.getenv("DEEPSEEK_NEWS_CACHE_PATH", ".runtime/deepseek_news_context.json")
NEWS_CACHE_HOURS = int(os.getenv("NEWS_CACHE_HOURS", "6"))
DEEPSEEK_NEWS_CONTEXT_LIMIT = int(os.getenv("DEEPSEEK_NEWS_CONTEXT_LIMIT", "3"))
DEEPSEEK_NEWS_CACHE_MAX_ENTRIES = int(os.getenv("DEEPSEEK_NEWS_CACHE_MAX_ENTRIES", "1000"))
DEEPSEEK_CASCADE_FILTER_ENABLED = os.getenv("DEEPSEEK_CASCADE_FILTER_ENABLED", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
DEEPSEEK_CASCADE_MAX_REVIEW = int(os.getenv("DEEPSEEK_CASCADE_MAX_REVIEW", "8"))
ENABLE_DEEPSEEK_MARKET_GATE = os.getenv("ENABLE_DEEPSEEK_MARKET_GATE", "0").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
DEEPSEEK_MARKET_GATE_CACHE_PATH = os.getenv("DEEPSEEK_MARKET_GATE_CACHE_PATH", ".runtime/deepseek_market_gate.json")
DEEPSEEK_MARKET_GATE_MIN_SIZE_FACTOR = float(os.getenv("DEEPSEEK_MARKET_GATE_MIN_SIZE_FACTOR", "0.25"))
DEEPSEEK_MARKET_GATE_RISK_OFF_SCORE_BONUS = float(os.getenv("DEEPSEEK_MARKET_GATE_RISK_OFF_SCORE_BONUS", "5"))
ENABLE_HOT_RANKS = os.getenv("ENABLE_HOT_RANKS", "0").lower() in ("1", "true", "yes", "on")
ENABLE_INDUSTRY_STRENGTH = os.getenv("ENABLE_INDUSTRY_STRENGTH", "0").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
EASTMONEY_TIMEOUT_SECONDS = float(os.getenv("EASTMONEY_TIMEOUT_SECONDS", "1"))
EASTMONEY_PAGE_SIZE = int(os.getenv("EASTMONEY_PAGE_SIZE", "500"))
EASTMONEY_MAX_PAGES = int(os.getenv("EASTMONEY_MAX_PAGES", "1"))
EASTMONEY_SORT_FIELD = os.getenv("EASTMONEY_SORT_FIELD", "f6")

# 回测校准脚本（calibrate.py）写出的权重覆盖文件；scoring/backtest 启动时若存在则加载。
WEIGHTS_OVERRIDE_PATH = os.getenv("WEIGHTS_OVERRIDE_PATH", ".runtime/weights.json")
TOMORROW_ITERATION_PATH = os.getenv("TOMORROW_ITERATION_PATH", ".runtime/tomorrow_iteration.json")
CALIBRATE_MIN_SAMPLES = int(os.getenv("CALIBRATE_MIN_SAMPLES", "30"))
CALIBRATE_IMPROVE_MARGIN = float(os.getenv("CALIBRATE_IMPROVE_MARGIN", "0.05"))
CALIBRATE_WALK_FORWARD_FOLDS = int(os.getenv("CALIBRATE_WALK_FORWARD_FOLDS", "4"))
CALIBRATE_MIN_COVERAGE = float(os.getenv("CALIBRATE_MIN_COVERAGE", "0.5"))
CALIBRATE_TOMORROW_DIRECTION_FOCUSED = os.getenv("CALIBRATE_TOMORROW_DIRECTION_FOCUSED", "1").lower() in (
    "1",
    "true",
    "yes",
    "on",
)

# 小市值策略的流通市值下限（元），过滤纯壳/退市风险股。默认 8 亿。
SMALLCAP_MIN_FLOAT_CAP = float(os.getenv("SMALLCAP_MIN_FLOAT_CAP", "800000000"))

SUPPORTED_PREFIXES = (
    "600",
    "601",
    "603",
    "605",
    "000",
    "001",
    "002",
    "003",
    "300",
    "301",
    "688",
)

MAIN_BOARD_PREFIXES = ("600", "601", "603", "605", "000", "001", "002", "003")
CHINEXT_PREFIXES = ("300", "301")
STAR_PREFIXES = ("688",)

MARKET_LABELS = {
    "all": "A股",
    "main": "主板",
    "chinext": "创业板",
    "star": "科创板",
}
# 三策略口径（不再保留旧策略兼容清单）
SNAPSHOT_STRATEGIES = (
    "short_term",
    "tomorrow_picks",
    "swing_picks",
)
ACTIVE_STRATEGIES = (
    "tomorrow_picks",
    "swing_picks",
)
