from typing import Dict, Iterable, List, Tuple

import pandas as pd

from ..normalization import (
    coerce_number,
    finite_series,
    is_supported_code,
    market_type,
    normalize_code,
    percentile_score,
)
from .theme_constants import CHOKEPOINT_CHAIN, TECH_THEMES
from .theme_scores import (
    CHOKEPOINT_INDUSTRY_LEADERS,
    CHOKEPOINT_KEYWORDS,
    SERENITY_REFERENCES,
    _chain_segment,
    _chokepoint_score,
    _tech_theme_score,
)
from .explanations import (
    PROFILE_COMPONENTS,
    TRADING_AGENTS_REFERENCE,
    _agent_bear_cases,
    _agent_bull_cases,
    _append_unique_reason,
    _attach_signal_explanation,
    _build_agent_committee,
    _build_long_term_reasons,
    _build_position_reasons,
    _build_reasons,
    _build_serenity_profile,
    _build_swing_reasons,
    _build_tech_potential_reasons,
    _build_tomorrow_reasons,
    _chase_risk,
    _data_coverage,
    _decision_score,
    _exit_action,
    _failure_reasons,
    _mark_tomorrow_intraday_watch,
    _overextension_risk,
    _sell_risk,
    _trade_action,
    _unique_strings,
    _verdict_tier,
    _weighted_score,
    _with_regime_reason,
    mark_backup_watch,
    mark_tomorrow_backup_watch,
)
from .candidate_filters import (
    HARD_FILTER_LABELS,
    _candidate_base_frame,
    _candidate_filter_masks,
    _combine_candidate_masks,
    _is_buyable_gain,
    candidate_filter_report,
    prepare_candidates,
)
from .constants import ALPHALITE_SIGNAL_COLUMNS, STRATEGY_LABELS
from .market_regime import (
    _history_breadth_metrics,
    _market_regime_breadth_frame,
    _market_regime_with_history,
    build_market_regime,
)
from .expected_return import (
    _attach_expected_return_prediction,
    _expected_return_rank_active,
    _ranking_gate_score,
)
from .risk import (
    _penalty_value,
    _set_positive_penalty,
    _smooth_penalty,
    _sum_penalty,
    _swing_risk_penalty,
    _swing_risk_penalty_parts,
    _tomorrow_risk_penalty,
    _tomorrow_risk_penalty_parts,
)
from .scoring_math import (
    _apply_overheat_damp,
    _close_location,
    _combine,
    _combine_details,
    _combined_speed,
    _composite_score,
    _execution_score,
    _factor_ic_multiplier,
    _factor_ic_payload,
    _has_signal,
    _horizon_meta,
    _horizon_row,
    _hot_rank_score,
    _market_regime_adjustment,
    _near_limit_up_risk,
    _not_overextended_score,
    _optional_factor_score,
    _overheat_damp_multiplier,
    _regime_component,
    _regime_component_from_profile,
    _regime_weight,
    _regime_weight_profile,
    _row_speed,
    _safe_corr,
    _score_context,
    _stddev,
    _tail_close_setup_score,
)
from .today_score import _score_row
from .theme_limits import (
    _infer_theme_from_row,
    _limit_tomorrow_display_concentration,
    _theme_count_allowed,
    _theme_round_robin,
    _tomorrow_display_theme_allowed,
    _tomorrow_theme_distribution,
    _tomorrow_theme_key,
    limit_theme_concentration,
)
from .tomorrow_score import (
    _tomorrow_backup_reject,
    _tomorrow_backup_rows,
    _tomorrow_historical_edge_score,
)
from .tomorrow_policy import (
    _parse_datetime_value,
    _time_parts,
    _tomorrow_analysis_window,
    _tomorrow_display_gate,
    _tomorrow_hard_reject,
    _tomorrow_intraday_relaxed_mode,
    _tomorrow_policy,
    _tomorrow_primary_eligibility,
    _tomorrow_primary_watch_limit,
    _tomorrow_quote_time,
)


__all__ = [
    'coerce_number',
    'finite_series',
    'is_supported_code',
    'market_type',
    'normalize_code',
    'percentile_score',
    'CHOKEPOINT_CHAIN',
    'TECH_THEMES',
    'CHOKEPOINT_INDUSTRY_LEADERS',
    'CHOKEPOINT_KEYWORDS',
    'SERENITY_REFERENCES',
    '_chain_segment',
    '_chokepoint_score',
    '_tech_theme_score',
    'PROFILE_COMPONENTS',
    'TRADING_AGENTS_REFERENCE',
    '_agent_bear_cases',
    '_agent_bull_cases',
    '_append_unique_reason',
    '_attach_signal_explanation',
    '_build_agent_committee',
    '_build_long_term_reasons',
    '_build_position_reasons',
    '_build_reasons',
    '_build_serenity_profile',
    '_build_swing_reasons',
    '_build_tech_potential_reasons',
    '_build_tomorrow_reasons',
    '_chase_risk',
    '_data_coverage',
    '_decision_score',
    '_exit_action',
    '_failure_reasons',
    '_mark_tomorrow_intraday_watch',
    '_overextension_risk',
    '_sell_risk',
    '_trade_action',
    '_unique_strings',
    '_verdict_tier',
    '_weighted_score',
    '_with_regime_reason',
    'mark_backup_watch',
    'mark_tomorrow_backup_watch',
    'HARD_FILTER_LABELS',
    '_candidate_base_frame',
    '_candidate_filter_masks',
    '_combine_candidate_masks',
    '_is_buyable_gain',
    'candidate_filter_report',
    'prepare_candidates',
    'ALPHALITE_SIGNAL_COLUMNS',
    'STRATEGY_LABELS',
    '_history_breadth_metrics',
    '_market_regime_breadth_frame',
    '_market_regime_with_history',
    'build_market_regime',
    '_attach_expected_return_prediction',
    '_expected_return_rank_active',
    '_ranking_gate_score',
    '_penalty_value',
    '_set_positive_penalty',
    '_smooth_penalty',
    '_sum_penalty',
    '_apply_overheat_damp',
    '_close_location',
    '_combine',
    '_combine_details',
    '_combined_speed',
    '_composite_score',
    '_execution_score',
    '_factor_ic_multiplier',
    '_factor_ic_payload',
    '_has_signal',
    '_horizon_meta',
    '_horizon_row',
    '_hot_rank_score',
    '_market_regime_adjustment',
    '_near_limit_up_risk',
    '_not_overextended_score',
    '_optional_factor_score',
    '_overheat_damp_multiplier',
    '_regime_component',
    '_regime_component_from_profile',
    '_regime_weight',
    '_regime_weight_profile',
    '_row_speed',
    '_safe_corr',
    '_score_context',
    '_score_row',
    '_stddev',
    '_swing_risk_penalty',
    '_swing_risk_penalty_parts',
    '_tail_close_setup_score',
    '_infer_theme_from_row',
    '_limit_tomorrow_display_concentration',
    '_theme_count_allowed',
    '_theme_round_robin',
    '_tomorrow_display_theme_allowed',
    '_tomorrow_theme_distribution',
    '_tomorrow_theme_key',
    'limit_theme_concentration',
    '_parse_datetime_value',
    '_time_parts',
    '_tomorrow_analysis_window',
    '_tomorrow_backup_reject',
    '_tomorrow_backup_rows',
    '_tomorrow_display_gate',
    '_tomorrow_hard_reject',
    '_tomorrow_historical_edge_score',
    '_tomorrow_intraday_relaxed_mode',
    '_tomorrow_policy',
    '_tomorrow_primary_eligibility',
    '_tomorrow_primary_watch_limit',
    '_tomorrow_quote_time',
    '_tomorrow_risk_penalty',
    '_tomorrow_risk_penalty_parts',
    'COMPONENT_FACTOR_KEYS',
    'STRATEGY_COMBINERS',
    'THRESHOLDS',
    'WEIGHTS',
    '_DEFAULT_THRESHOLDS',
    '_DEFAULT_WEIGHTS',
    '_load_weight_overrides',
    'score_today_candidates',
    'score_tomorrow_candidates',
    'score_swing_candidates',
]

from .weights import (
    COMPONENT_FACTOR_KEYS,
    STRATEGY_COMBINERS,
    THRESHOLDS,
    WEIGHTS,
    _DEFAULT_THRESHOLDS,
    _DEFAULT_WEIGHTS,
    _load_weight_overrides,
)


def score_today_candidates(
    df: pd.DataFrame,
    hot_ranks: Dict[str, int],
    industry_strength: Dict[str, float],
    sentiment_lookup: Dict[str, Dict[str, object]],
    top_n: int = 10,
    market_filter: str = "all",
    market_regime: Dict[str, object] = None,
    capture_candidate_pool: bool = False,
    scoring_context: Dict[str, object] = None,
) -> Tuple[Dict[str, List[Dict[str, object]]], Dict[str, object]]:
    from ..strategies.today import TodayScorer

    return TodayScorer().score(
        df,
        hot_ranks,
        industry_strength,
        sentiment_lookup,
        top_n=top_n,
        market_filter=market_filter,
        market_regime=market_regime,
        capture_candidate_pool=capture_candidate_pool,
        scoring_context=scoring_context,
    )


def score_tomorrow_candidates(
    df: pd.DataFrame,
    top_n: int = 50,
    market_filter: str = "all",
    market_regime: Dict[str, object] = None,
    display_cap: int = None,
    expected_return_samples: Iterable[Dict[str, object]] = None,
    use_expected_return_ranking: bool = False,
    capture_candidate_pool: bool = False,
) -> Tuple[List[Dict[str, object]], Dict[str, object]]:
    from ..strategies.tomorrow import TomorrowScorer

    return TomorrowScorer().score(
        df,
        top_n=top_n,
        market_filter=market_filter,
        market_regime=market_regime,
        display_cap=display_cap,
        expected_return_samples=expected_return_samples,
        use_expected_return_ranking=use_expected_return_ranking,
        capture_candidate_pool=capture_candidate_pool,
    )


def score_swing_candidates(
    df: pd.DataFrame,
    top_n: int = 30,
    market_filter: str = "all",
    market_regime: Dict[str, object] = None,
    expected_return_samples: Iterable[Dict[str, object]] = None,
    use_expected_return_ranking: bool = False,
    capture_candidate_pool: bool = False,
) -> Tuple[List[Dict[str, object]], Dict[str, object]]:
    from ..strategies.swing_2_5d import SwingScorer

    return SwingScorer().score(
        df,
        top_n=top_n,
        market_filter=market_filter,
        market_regime=market_regime,
        expected_return_samples=expected_return_samples,
        use_expected_return_ranking=use_expected_return_ranking,
        capture_candidate_pool=capture_candidate_pool,
    )
